apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - namespace.yaml
  - prometheus/
  - loki/
  - tempo/
  - otel-collector/
  - grafana/
  - fluent-bit/

commonLabels:
  app.kubernetes.io/part-of: colorforge-observability
