apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - datasources.yaml
  - dashboards-configmap.yaml
  - logs-dashboard-configmap.yaml
  - deployment.yaml
  - service.yaml
