apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backstage

resources:
  - namespace.yaml
  - postgres.yaml
  - secret.yaml
  - configmap.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  app.kubernetes.io/part-of: colorforge
  app.kubernetes.io/managed-by: kustomize
