apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
stringData:
  # GitHub Personal Access Token (necess√°rio para catalog)
  # Criar em: https://github.com/settings/tokens
  # Scopes: repo, read:org, read:user
  GITHUB_TOKEN: "ghp_CHANGE_ME"

  # SonarQube Token (opcional)
  SONARQUBE_TOKEN: ""
