apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: colorforge

resources:
  - cloudflared-deployment.yaml
  - cloudflared-configmap.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: colorforge
      app.kubernetes.io/managed-by: kustomize
