apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mycolorforge

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - api-deployment.yaml
  - frontend-deployment.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: mycolorforge
  app.kubernetes.io/managed-by: kustomize
